[phases.setup]
nixPkgs = ["php82", "composer", "git", "curl"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-scripts",
    "composer dump-autoload --optimize"
]

[phases.build]
cmds = [
    "chmod +x railway-setup.sh"
]

[start]
cmd = "bash railway-setup.sh && php artisan serve --host=0.0.0.0 --port=$PORT" 