[phases.setup]
nixPkgs = ["php82", "composer", "git"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader --no-scripts"]

[phases.build]
cmds = [
    "php artisan key:generate --no-interaction || true",
    "php artisan storage:link --no-interaction || true"
] 